In [ ]:
# variables in python

In [1]:
print("this is sparta")

this is sparta


In [5]:
student = "Sam"

In [6]:
student

'Sam'

In [7]:
student = "Matt"

In [8]:
student

'Matt'

In [10]:
student = "Bob"

In [11]:
student

'Bob'

In [17]:
# data types in python

In [18]:
a1 = 10
a1

10

In [19]:
type(a1)

int

In [20]:
a1 = 3.14

In [21]:
type(a1)

float

In [24]:
a1 = True

In [25]:
a1

True

In [26]:
type(a1)

bool

In [27]:
a1 = "hello"

In [28]:
a1

'hello'

In [29]:
type(a1)

str

In [30]:
a1 = 3 + 4j
a1

(3+4j)

In [31]:
type(a1)

complex

In [32]:
# operators in python

In [33]:
a = 10
b = 20
a, b

(10, 20)

In [34]:
a + b

30

In [35]:
a - b

-10

In [36]:
a * b

200

In [37]:
a / b

0.5

In [39]:
a > b

False

In [40]:
a >= b

False

In [41]:
a == b

False

In [42]:
a != b

True

In [43]:
a < b

True

In [44]:
a <= b

True

In [45]:
std = "martha"
std

'martha'

In [ ]:
# strings

In [46]:
str1 = "this is my first string"
str1

'this is my first string'

In [47]:
str2 = """ this is my second string.
i am using docstring here.
"""

In [48]:
str2

' this is my second string.\ni am using docstring here.\n'

In [3]:
my_string = "My name is Zahid"
my_string

'My name is Zahid'

In [51]:
my_string[0]

'M'

In [52]:
my_string[-1]

'd'

In [4]:
my_string[4:8]

'ame '

In [5]:
my_string[8:]

'is Zahid'

In [6]:
my_string[::-1]

'dihaZ si eman yM'

In [7]:
len(my_string)

16

In [8]:
my_string.lower()

'my name is zahid'

In [9]:
my_string.upper()

'MY NAME IS ZAHID'

In [10]:
my_string.capitalize()

'My name is zahid'

In [12]:
my_string.replace("Zahid","Jewel")

'My name is Jewel'

In [14]:
my_string.count("a")

2

In [15]:
s1 = "this is sparta"

In [16]:
s1.find("is")

2

In [17]:
s1.split()

['this', 'is', 'sparta']

In [18]:
s2 = " this is my country "

In [19]:
s2.strip()

'this is my country'

In [20]:
s2.rstrip()

' this is my country'

In [21]:
s2.lstrip()

'this is my country '

In [22]:
s3 = "apple,banana,orange,mango"

In [23]:
s3.split(",")

['apple', 'banana', 'orange', 'mango']

In [24]:
email = 'zahidulislamssf@gmail.com'

In [25]:
email

'zahidulislamssf@gmail.com'

In [26]:
email.split('@')

['zahidulislamssf', 'gmail.com']

In [27]:
 # python data structures

In [28]:
# tuples

In [29]:
tup1 = (1,True,3.14,4+3j)

In [30]:
tup1

(1, True, 3.14, (4+3j))

In [31]:
type(tup1)

tuple

In [33]:
tup1[0]

1

In [34]:
tup1[-1]

(4+3j)

In [36]:
tup1[1:4]

(True, 3.14, (4+3j))

In [37]:
 len(tup1)

4

In [38]:
t1 = (1,2,3)
t2 = (4,5,6)

In [39]:
t1 + t2

(1, 2, 3, 4, 5, 6)

In [40]:
len(t1 + t2)

6

In [41]:
t1, t2 

((1, 2, 3), (4, 5, 6))

In [45]:
t1*3

(1, 2, 3, 1, 2, 3, 1, 2, 3)

In [46]:
max(t1)

3

In [47]:
min(t1)

1

In [48]:
max(t2)

6

In [49]:
min(t2)

4

In [50]:
# list

In [51]:
L = [4, 9, 2, 3, 5, 7, 8, 1, 6, 0]
L

[4, 9, 2, 3, 5, 7, 8, 1, 6, 0]

In [52]:
len(L)

10

In [53]:
sorted(L)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [54]:
L

[4, 9, 2, 3, 5, 7, 8, 1, 6, 0]

In [56]:
L.sort()

In [57]:
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [59]:
type(L)

list

In [60]:
L[0]

0

In [61]:
L[2:5]

[2, 3, 4]

In [62]:
L[-1]

9

In [63]:
L[::2]

[0, 2, 4, 6, 8]

In [64]:
L[::-1]

[9, 8, 7, 6, 5, 4, 3, 2, 1, 0]

In [65]:
L.append(11)

In [66]:
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 11]

In [67]:
L.pop()

11

In [68]:
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [69]:
L.reverse()

In [70]:
L

[9, 8, 7, 6, 5, 4, 3, 2, 1, 0]

In [71]:
L.insert(4,13)

In [72]:
L

[9, 8, 7, 6, 13, 5, 4, 3, 2, 1, 0]

In [74]:
L.remove(3)

In [75]:
L

[9, 8, 7, 6, 13, 5, 4, 2, 1, 0]

In [76]:
sum(L)

55

In [78]:
L1 = [4,9,2]
L2 = [3,5,7,8]

In [79]:
L1 + L2

[4, 9, 2, 3, 5, 7, 8]

In [80]:
L1*3

[4, 9, 2, 4, 9, 2, 4, 9, 2]

In [81]:
# dictionary

In [82]:
d1 = {"apple": 50 , "orange": 80, "gauva": 50, "banana": 30}

In [83]:
type(d1)

dict

In [84]:
d1.keys()

dict_keys(['apple', 'orange', 'gauva', 'banana'])

In [85]:
d1.values()

dict_values([50, 80, 50, 30])

In [87]:
d1.items()

dict_items([('apple', 50), ('orange', 80), ('gauva', 50), ('banana', 30)])

In [88]:
d1["date"] = 50

In [89]:
d1

{'apple': 50, 'orange': 80, 'gauva': 50, 'banana': 30, 'date': 50}

In [90]:
len(d1)

5

In [97]:
sorted(d1)

['apple', 'banana', 'date', 'gauva', 'orange']

In [98]:
fruit1 = {'apple': 50, 'orange': 80, 'gauva': 50}
fruit2 = {'banana': 30, 'date': 50}

In [99]:
fruit1.update(fruit2)

In [100]:
fruit1

{'apple': 50, 'orange': 80, 'gauva': 50, 'banana': 30, 'date': 50}

In [101]:
fruit1.pop("apple")

50

In [103]:
fruit1

{'orange': 80, 'gauva': 50, 'banana': 30, 'date': 50}

In [104]:
# set

In [105]:
s1 = {4,9,2,3,5}
s2 = {8,1,6,0,7}

In [106]:
type(s1)

set

In [107]:
len(s1)

5

In [108]:
len(s2)

5

In [110]:
s1.add(11)

In [111]:
s1

{2, 3, 4, 5, 9, 11}

In [112]:
s2.update([13,17,19])

In [113]:
s2

{0, 1, 6, 7, 8, 13, 17, 19}

In [114]:
s2.remove(0)

In [115]:
s2

{1, 6, 7, 8, 13, 17, 19}

In [116]:
s3 = {4,4,9,9,9,2,3,3,3,3,5,7,7,8,1,1,1,1,6}

In [117]:
s3

{1, 2, 3, 4, 5, 6, 7, 8, 9}

In [120]:
s1.union(s2)

{1, 2, 3, 4, 5, 6, 7, 8, 9, 11, 13, 17, 19}

In [122]:
s1.intersection(s2)

set()

In [123]:
s1.intersection(s3)

{2, 3, 4, 5, 9}

In [ ]:
# control flows

In [1]:
# if statement

In [2]:
a = 10
b = 20

In [3]:
if b > a:
    print(f"{b} is greater than {a}")
else:
    print(f"{a} is greater than {b}")

20 is greater than 10


In [4]:
a = 10
b = 20
c = 30

In [5]:
if a>b and a> c:
    print(f"{a} is greatest")
elif b>a and b>c:
    print(f"{b} is the greatest")
else:
    print(f"{c} is the greatest")

30 is the greatest


In [6]:
# if with tuple

In [7]:
t1 = ('a','b','c')

In [9]:
if 'a' in t1:
    print(f"{a} is present in t1")

10 is present in t1


In [10]:
if 'z' in t1:
    print("z is present in t1")
else:
    print("z is not present in t1")

z is not present in t1


In [11]:
# if with list

In [12]:
L = [4,9,2]

In [13]:
if L[1] == 9:
    L[1] = 1

In [14]:
L

[4, 1, 2]

In [15]:
# if with dictionary

In [16]:
d1 = {"key1": 10, "key2": 20, "key3": 30}

In [17]:
if d1["key3"] == 30:
    d1["key3"] += 100

In [18]:
d1

{'key1': 10, 'key2': 20, 'key3': 130}

In [19]:
# looping statements

In [20]:
# for loop

In [22]:
i = 1
while i <= 10:
    print(i,end=" ")
    i = i + 1

1 2 3 4 5 6 7 8 9 10 

In [23]:
i = 1
n = 5
while i <= 10:
    print(f"{n} X {i} = {n*i}",end="\n")
    i = i + 1

5 X 1 = 5
5 X 2 = 10
5 X 3 = 15
5 X 4 = 20
5 X 5 = 25
5 X 6 = 30
5 X 7 = 35
5 X 8 = 40
5 X 9 = 45
5 X 10 = 50


In [25]:
# while with list

In [26]:
L = [4, 9, 2, 3, 5, 7, 8, 1, 6, 0]

In [27]:
i = 0
while i < len(L):
    print(L[i], end=" ")
    i = i + 1

4 9 2 3 5 7 8 1 6 0 

In [28]:
i = 0
while i < len(L):
    L[i] = L[i]**2
    i = i + 1

In [29]:
L

[16, 81, 4, 9, 25, 49, 64, 1, 36, 0]

In [30]:
# for loop

In [31]:
list1 = ["mango", "apple", "orange", "grapes"]

In [32]:
for fruit in list1:
    print(fruit,end=" ")

mango apple orange grapes 

In [35]:
colors = ["crimson", "blue", "black", "white"]
elements = ["chair", "book", "laptop","mobile"]

In [37]:
for color in colors:
    for element in elements:
        print(f"{color} - {element}")

crimson - chair
crimson - book
crimson - laptop
crimson - mobile
blue - chair
blue - book
blue - laptop
blue - mobile
black - chair
black - book
black - laptop
black - mobile
white - chair
white - book
white - laptop
white - mobile


In [ ]:
# functions

In [38]:
def greet():
    print("Welcome. how are you?")

In [39]:
greet()

Welcome. how are you?


In [40]:
def increment(x):
    x = x + 10
    return x

In [42]:
increment(9)

19

In [43]:
increment(5)

15

In [44]:
def evenOdd(n):
    if n%2==0:
        return "even"
    elif n%2==1:
        return "odd"

In [45]:
evenOdd(13)

'odd'

In [46]:
evenOdd(8)

'even'

In [48]:
# lambda function

In [49]:
lambda x:x+3

<function __main__.<lambda>(x)>

In [50]:
g = lambda x:x+3

In [51]:
g(2)

5

In [52]:
g(7)

10

In [53]:
f = lambda x : x**2

In [54]:
f(8)

64

In [55]:
# filter

In [56]:
L = [4, 9, 2, 3, 5, 7, 8, 1, 6, 0]

In [62]:
list(filter(lambda x: x%2==0,L))

[4, 2, 8, 6, 0]

In [60]:
M = list(filter(lambda x: x%2==0,L))

In [61]:
M

[4, 2, 8, 6, 0]

In [63]:
list(filter(lambda x: x%2==1, L))

[9, 3, 5, 7, 1]

In [64]:
# map

In [65]:
L = [4, 9, 2, 3, 5, 7, 8, 1, 6, 0]

In [66]:
list(map(lambda x: x**2,L))

[16, 81, 4, 9, 25, 49, 64, 1, 36, 0]

In [67]:
N = list(map(lambda x: x**3,L))

In [70]:
N

[64, 729, 8, 27, 125, 343, 512, 1, 216, 0]

In [ ]:
# reduce

In [72]:
from functools import reduce

In [ ]:
L = [4, 9, 2, 3, 5, 7, 8, 1, 6, 0]

In [71]:
reduce(lambda x,y:x+y,L)

45

In [73]:
product = reduce(lambda x,y:x*y, L)

In [74]:
product

0

In [75]:
# object oriented programming 

In [76]:
class Phone:
    def make_call(self):
        print("making the call")
    
    def play_game(self):
        print("playing game")

In [77]:
p1 = Phone()

In [78]:
p1.make_call()

making the call


In [79]:
p1.play_game()

playing game


In [80]:
# parameters to the calss 

In [86]:
class Phone:
    
    def set_color(self,color):
        self.color = color
        
    def set_cost(self,cost):
        self.cost = cost
    
    def show_color(self):
        return self.color
    
    def show_cost(self):
        return self.cost
        
    def make_call(self):
        print("making the call")
    
    def play_game(self):
        print("playing game")

In [88]:
p2 = Phone()

In [89]:
p2.set_color("crimson")

In [90]:
p2.set_cost(12000)

In [91]:
p2.show_color()

'crimson'

In [92]:
p2.show_cost()

12000

In [93]:
p2.make_call()

making the call


In [94]:
p2.play_game()

playing game


In [95]:
# class with constructor

In [108]:
class Employee:
    def __init__(self, name, age, salary, gender):
        self.name = name
        self.age = age
        self.salary = salary
        self.gender = gender
    
    def employee_details(self):
        print(f"Name:{self.name}\nAge:{self.age}\nSalaray:{self.salary}\nGender:{self.gender}")

In [109]:
e1 = Employee("Sam",32,85000,"Male")

In [110]:
e1.employee_details()

Name:Sam
Age:32
Salaray:85000
Gender:Male


In [111]:
# inheritance

In [114]:
class Vehicle:
    def __init__(self,mileage,cost):
        self.mileage = mileage
        self.cost = cost
    
    def show_details(self):
        print("I am a vehicle")
        print(f"Mileage = {self.mileage}")
        print(f"Cost = {self.cost}")

In [115]:
v1 = Vehicle(500,500)
v1.show_details()

I am a vehicle
Mileage = 500
Cost = 500


In [116]:
class Car(Vehicle):
    def show_car(self):
        print("i am a car")

In [117]:
c1 = Car(200, 1200)

In [118]:
c1.show_details()

I am a vehicle
Mileage = 200
Cost = 1200


In [119]:
c1.show_car()

i am a car


In [120]:
# constructor overriding

In [121]:
class Vehicle:
    def __init__(self,mileage,cost):
        self.mileage = mileage
        self.cost = cost
    
    def show_details(self):
        print("I am a vehicle")
        print(f"Mileage = {self.mileage}")
        print(f"Cost = {self.cost}")

In [123]:
class Car(Vehicle):
    
    def __init__(self,mileage,cost,tyres,hp):
        super().__init__(mileage,cost)
        self.tyres = tyres
        self.hp = hp
        
    def show_car_details(self):
        print("i am a car")
        print(f"Mileage = {self.mileage}")
        print(f"Cost = {self.cost}")
        print(f"No of tyres = {self.tyres}")
        print(f"Horse power = {self.hp}")

In [124]:
c1 = Car(20,1200,4,300)

In [125]:
c1.show_details()

I am a vehicle
Mileage = 20
Cost = 1200


In [127]:
c1.show_car_details()

i am a car
Mileage = 20
Cost = 1200
No of tyres = 4
Horse power = 300


In [152]:
# types of inheritance in python

In [ ]:
# multiple inheritance

In [129]:
class Parent1():
    def assign_string_one(self,str1):
        self.str1 = str1
    
    def show_string_one(self):
        return self.str1

In [130]:
class Parent2():
    def assign_string_two(self,str2):
        self.str2 = str2
    
    def show_string_two(self):
        return self.str2

In [139]:
class Child(Parent1, Parent2):
    def assign_string_three(self,str3):
        self.str3 = str3;
    
    def show_string_three(self):
        return self.str3

In [140]:
p1 = Parent1()

In [141]:
p1.assign_string_one("cpp")

In [142]:
p1.show_string_one()

'cpp'

In [143]:
p2 = Parent2()

In [144]:
p2.assign_string_two("java")

In [145]:
p2.show_string_two()

'java'

In [136]:
c1 = Child()

In [148]:
c1.assign_string_three("javascript")
c1.assign_string_one("C")
c1.assign_string_two("python")

In [149]:
c1.show_string_three()

'javascript'

In [150]:
c1.show_string_one()

'C'

In [151]:
c1.show_string_two()

'python'

In [153]:
# multi level inheritance

In [178]:
class Parent():
    def set_name(self, name):
        self.name = name
    
    def show_name(self):
        print(f"Name = {self.name}")

In [179]:
class Child(Parent):
    def set_age(self, age):
        self.age = age
    
    def show_age(self):
        print(f"Age = {self.age}")

In [181]:
class GrandChild(Child):
    def set_gender(self, gender):
        self.gender = gender
    
    def show_gender(self):
        print(f"Gender = {self.gender}")

In [182]:
p1 = Parent()
p1.set_name("Zahid")
p1.show_name()

Name = Zahid


In [183]:
c1 = Child()
c1.set_age(29)
c1.set_name("Robi")
c1.show_name()
c1.show_age()

Name = Robi
Age = 29


In [184]:
g1 = GrandChild()
g1.set_name("Kiran")
g1.set_age(22)
g1.set_gender("Female")
g1.show_name()
g1.show_age()
g1.show_gender()

Name = Kiran
Age = 22
Gender = Female


In [185]:
# python libraries

In [1]:
# numpy

In [3]:
import numpy as np

In [4]:
n1 = np.array([4,9,2,3,5])

In [5]:
n1

array([4, 9, 2, 3, 5])

In [6]:
n2 = np.array([[4,9,2],[3,5,7]])
n2

array([[4, 9, 2],
       [3, 5, 7]])

In [8]:
n3 = np.array([[4,9,2],[3,5,7],[8,1,6]])
n3

array([[4, 9, 2],
       [3, 5, 7],
       [8, 1, 6]])

In [9]:
type(n1)

numpy.ndarray

In [11]:
type(n2)

numpy.ndarray

In [12]:
type(n3)

numpy.ndarray

In [13]:
n4 = np.zeros((5,5))
n4

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [14]:
n5 = np.zeros((4,3))
n5

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [15]:
n6 = np.full((3,3),1)
n6

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [16]:
n7 = np.full((2,2),0)

In [17]:
n7

array([[0, 0],
       [0, 0]])

In [18]:
n8 = np.arange(10,20)

In [19]:
n8

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [20]:
n9 = np.arange(1,14,2)
n9

array([ 1,  3,  5,  7,  9, 11, 13])

In [21]:
n10 = np.arange(5,55,5)
n10

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [22]:
m1 = np.random.randint(1,100,5)
m1

array([47, 68,  6, 12, 87])

In [23]:
m2 = np.random.randint(1,500,10)
m2

array([221,  12, 195,  42, 155, 403, 412, 209,  44,  42])

In [24]:
m1.shape

(5,)

In [25]:
m3 = np.array([[4,9],[2,3]])
m3

array([[4, 9],
       [2, 3]])

In [26]:
m3.shape

(2, 2)

In [27]:
m3.shape = (1,4)
m3

array([[4, 9, 2, 3]])

In [5]:
m4 = np.array([[4,9,2],[3,5,7],[8,1,6]])
m4

array([[4, 9, 2],
       [3, 5, 7],
       [8, 1, 6]])

In [29]:
m4.shape

(3, 3)

In [30]:
m4.shape = (1,9)

In [31]:
m4

array([[4, 9, 2, 3, 5, 7, 8, 1, 6]])

In [13]:
m4.shape

(3, 3)

In [15]:
# jointing numpy arrays

In [7]:
n1 = np.array([10,20,30])
n2 = np.array([40,50,60])

In [8]:
n3 = np.vstack((n1,n2))

In [9]:
n3

array([[10, 20, 30],
       [40, 50, 60]])

In [10]:
n4 = np.hstack((n1,n2))
n4

array([10, 20, 30, 40, 50, 60])

In [11]:
n5 = np.column_stack((n1,n2))

In [12]:
n5

array([[10, 40],
       [20, 50],
       [30, 60]])

In [16]:
# numpy intersection and difference

In [17]:
n1 = np.array([10,20,30,40,50,60])
n2 = np.array([50,60,70,80,90])

In [18]:
np.intersect1d(n1,n2)

array([50, 60])

In [19]:
np.setdiff1d(n1,n2)

array([10, 20, 30, 40])

In [20]:
np.setdiff1d(n2,n1)

array([70, 80, 90])

In [21]:
# numpy array mathematics

In [22]:
n1 = np.array([4,9,2])
n2 = np.array([3,5,7])

In [23]:
np.sum([n1,n2])

30

In [24]:
np.sum([n1,n2],axis=0)

array([ 7, 14,  9])

In [25]:
np.sum([n1,n2],axis=1)

array([15, 15])

In [26]:
n1 = np.array([10,20,30,40])
n1 = n1 + 1
n1

array([11, 21, 31, 41])

In [27]:
n1 = n1 - 1
n1

array([10, 20, 30, 40])

In [35]:
n1 = n1*2
n1

array([ 5., 10., 15., 20.])

In [33]:
n1 = n1 / 2

In [34]:
n1

array([ 2.5,  5. ,  7.5, 10. ])

In [36]:
# math functions in numpy

In [37]:
n1 = np.array([10,20,30,40,50,60,70])
np.mean(n1)

40.0

In [38]:
np.median(n1)

40.0

In [41]:
np.std(n1)

20.0

In [42]:
# numpy save and load

In [43]:
n1 = np.array([4, 9, 2, 3, 5, 7, 8, 1, 6, 0])
n1

array([4, 9, 2, 3, 5, 7, 8, 1, 6, 0])

In [44]:
np.save("my_numpy",n1)

In [45]:
n2 = np.load("my_numpy.npy")

In [46]:
n2

array([4, 9, 2, 3, 5, 7, 8, 1, 6, 0])

In [47]:
np.load("my_numpy.npy")

array([4, 9, 2, 3, 5, 7, 8, 1, 6, 0])

In [48]:
# pandas

In [49]:
# pandas series object

In [50]:
import pandas as pd

In [51]:
s1 = pd.Series([1,2,3,4,5])
s1

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [52]:
type(s1)

pandas.core.series.Series

In [53]:
# changing index

In [54]:
s1 = pd.Series([4,9,2,3,5],index=['a','b','c','d','e'])

In [55]:
s1

a    4
b    9
c    2
d    3
e    5
dtype: int64

In [56]:
# series object from dictionary

In [57]:
di = {'a':10, 'b':20, 'c':30}
pd.Series(di)

a    10
b    20
c    30
dtype: int64

In [58]:
# changing index position

In [59]:
pd.Series({'a':10, 'b':20, 'c':30}, index=['c','a','b'])

c    30
a    10
b    20
dtype: int64

In [60]:
# extracting individual elements

In [61]:
s1 = pd.Series([4,9,2,3,5,7,8,1,6,0])
s1[3]

3

In [62]:
s1[:4]

0    4
1    9
2    2
3    3
dtype: int64

In [63]:
s1[-3:]

7    1
8    6
9    0
dtype: int64

In [64]:
s1[3:6]

3    3
4    5
5    7
dtype: int64

In [65]:
s1[::-1]

9    0
8    6
7    1
6    8
5    7
4    5
3    3
2    2
1    9
0    4
dtype: int64

In [66]:
# basic math operations on series

In [67]:
s1 = pd.Series([4,9,2,3,5,7])
s2 = pd.Series([8,1,6,0])

In [68]:
s1+5

0     9
1    14
2     7
3     8
4    10
5    12
dtype: int64

In [69]:
s1 + s2

0    12.0
1    10.0
2     8.0
3     3.0
4     NaN
5     NaN
dtype: float64

In [70]:
# pandas dataframe

In [71]:
pd.DataFrame({"Name":['Bob','Sam','Anna'],"Marks":[76,25,92]})

Name  Marks
0   Bob     76
1   Sam     25
2  Anna     92

In [73]:
# dataframe built-in functions

In [75]:
real_state = pd.read_csv('realestate.csv')

In [76]:
real_state.head()

street        city    zip state  beds  baths  sq__ft  \
0      3526 HIGH ST  SACRAMENTO  95838    CA     2      1     836   
1       51 OMAHA CT  SACRAMENTO  95823    CA     3      1    1167   
2    2796 BRANCH ST  SACRAMENTO  95815    CA     2      1     796   
3  2805 JANETTE WAY  SACRAMENTO  95815    CA     2      1     852   
4   6001 MCMAHON DR  SACRAMENTO  95824    CA     2      1     797   

          type                     sale_date  price   latitude   longitude  
0  Residential  Wed May 21 00:00:00 EDT 2008  59222  38.631913 -121.434879  
1  Residential  Wed May 21 00:00:00 EDT 2008  68212  38.478902 -121.431028  
2  Residential  Wed May 21 00:00:00 EDT 2008  68880  38.618305 -121.443839  
3  Residential  Wed May 21 00:00:00 EDT 2008  69307  38.616835 -121.439146  
4  Residential  Wed May 21 00:00:00 EDT 2008  81900  38.519470 -121.435768

In [77]:
real_state.tail()

street             city    zip state  beds  baths  sq__ft  \
980   9169 GARLINGTON CT       SACRAMENTO  95829    CA     4      3    2280   
981      6932 RUSKUT WAY       SACRAMENTO  95823    CA     3      2    1477   
982    7933 DAFFODIL WAY   CITRUS HEIGHTS  95610    CA     3      2    1216   
983     8304 RED FOX WAY        ELK GROVE  95758    CA     4      2    1685   
984  3882 YELLOWSTONE LN  EL DORADO HILLS  95762    CA     3      2    1362   

            type                     sale_date   price   latitude   longitude  
980  Residential  Thu May 15 00:00:00 EDT 2008  232425  38.457679 -121.359620  
981  Residential  Thu May 15 00:00:00 EDT 2008  234000  38.499893 -121.458890  
982  Residential  Thu May 15 00:00:00 EDT 2008  235000  38.708824 -121.256803  
983  Residential  Thu May 15 00:00:00 EDT 2008  235301  38.417000 -121.397424  
984  Residential  Thu May 15 00:00:00 EDT 2008  235738  38.655245 -121.075915

In [79]:
real_state.shape

(985, 12)

In [80]:
real_state.describe

<bound method NDFrame.describe of                               street             city    zip state  beds  \
0                       3526 HIGH ST       SACRAMENTO  95838    CA     2   
1                        51 OMAHA CT       SACRAMENTO  95823    CA     3   
2                     2796 BRANCH ST       SACRAMENTO  95815    CA     2   
3                   2805 JANETTE WAY       SACRAMENTO  95815    CA     2   
4                    6001 MCMAHON DR       SACRAMENTO  95824    CA     2   
5                 5828 PEPPERMILL CT       SACRAMENTO  95841    CA     3   
6                6048 OGDEN NASH WAY       SACRAMENTO  95842    CA     3   
7                      2561 19TH AVE       SACRAMENTO  95820    CA     3   
8    11150 TRINITY RIVER DR Unit 114   RANCHO CORDOVA  95670    CA     2   
9                       7325 10TH ST        RIO LINDA  95673    CA     3   
10                  645 MORRISON AVE       SACRAMENTO  95838    CA     3   
11                     4085 FAWN CIR       SACRAMENTO 

In [81]:
real_state.iloc[0:3,0:2]

street        city
0    3526 HIGH ST  SACRAMENTO
1     51 OMAHA CT  SACRAMENTO
2  2796 BRANCH ST  SACRAMENTO

In [82]:
real_state.iloc[5:10,2:4]

zip state
5  95841    CA
6  95842    CA
7  95820    CA
8  95670    CA
9  95673    CA

In [83]:
real_state.iloc[0:10,]

street            city    zip state  beds  baths  \
0                     3526 HIGH ST      SACRAMENTO  95838    CA     2      1   
1                      51 OMAHA CT      SACRAMENTO  95823    CA     3      1   
2                   2796 BRANCH ST      SACRAMENTO  95815    CA     2      1   
3                 2805 JANETTE WAY      SACRAMENTO  95815    CA     2      1   
4                  6001 MCMAHON DR      SACRAMENTO  95824    CA     2      1   
5               5828 PEPPERMILL CT      SACRAMENTO  95841    CA     3      1   
6              6048 OGDEN NASH WAY      SACRAMENTO  95842    CA     3      2   
7                    2561 19TH AVE      SACRAMENTO  95820    CA     3      1   
8  11150 TRINITY RIVER DR Unit 114  RANCHO CORDOVA  95670    CA     2      2   
9                     7325 10TH ST       RIO LINDA  95673    CA     3      2   

   sq__ft         type                     sale_date  price   latitude  \
0     836  Residential  Wed May 21 00:00:00 EDT 2008  59222  38.631913   
1    1167  Residential  Wed May 21 00:00:00 EDT 2008  68212  38.478902   
2     796  Residential  Wed May 21 00:00:00 EDT 2008  68880  38.618305   
3     852  Residential  Wed May 21 00:00:00 EDT 2008  69307  38.616835   
4     797  Residential  Wed May 21 00:00:00 EDT 2008  81900  38.519470   
5    1122        Condo  Wed May 21 00:00:00 EDT 2008  89921  38.662595   
6    1104  Residential  Wed May 21 00:00:00 EDT 2008  90895  38.681659   
7    1177  Residential  Wed May 21 00:00:00 EDT 2008  91002  38.535092   
8     941        Condo  Wed May 21 00:00:00 EDT 2008  94905  38.621188   
9    1146  Residential  Wed May 21 00:00:00 EDT 2008  98937  38.700909   

    longitude  
0 -121.434879  
1 -121.431028  
2 -121.443839  
3 -121.439146  
4 -121.435768  
5 -121.327813  
6 -121.351705  
7 -121.481367  
8 -121.270555  
9 -121.442979

In [86]:
real_state.loc[0:5,("city","street","state")]

city              street state
0  SACRAMENTO        3526 HIGH ST    CA
1  SACRAMENTO         51 OMAHA CT    CA
2  SACRAMENTO      2796 BRANCH ST    CA
3  SACRAMENTO    2805 JANETTE WAY    CA
4  SACRAMENTO     6001 MCMAHON DR    CA
5  SACRAMENTO  5828 PEPPERMILL CT    CA

In [87]:
real_state.loc[0:5,("street","city","zip","state")]

street        city    zip state
0        3526 HIGH ST  SACRAMENTO  95838    CA
1         51 OMAHA CT  SACRAMENTO  95823    CA
2      2796 BRANCH ST  SACRAMENTO  95815    CA
3    2805 JANETTE WAY  SACRAMENTO  95815    CA
4     6001 MCMAHON DR  SACRAMENTO  95824    CA
5  5828 PEPPERMILL CT  SACRAMENTO  95841    CA

In [91]:
real_state.drop("city",axis=1)

street    zip state  beds  baths  sq__ft  \
0                       3526 HIGH ST  95838    CA     2      1     836   
1                        51 OMAHA CT  95823    CA     3      1    1167   
2                     2796 BRANCH ST  95815    CA     2      1     796   
3                   2805 JANETTE WAY  95815    CA     2      1     852   
4                    6001 MCMAHON DR  95824    CA     2      1     797   
5                 5828 PEPPERMILL CT  95841    CA     3      1    1122   
6                6048 OGDEN NASH WAY  95842    CA     3      2    1104   
7                      2561 19TH AVE  95820    CA     3      1    1177   
8    11150 TRINITY RIVER DR Unit 114  95670    CA     2      2     941   
9                       7325 10TH ST  95673    CA     3      2    1146   
10                  645 MORRISON AVE  95838    CA     3      2     909   
11                     4085 FAWN CIR  95823    CA     3      2    1289   
12                   2930 LA ROSA RD  95815    CA     1      1     871   
13                     2113 KIRK WAY  95822    CA     3      1    1020   
14               4533 LOCH HAVEN WAY  95842    CA     2      2    1022   
15                    7340 HAMDEN PL  95842    CA     2      2    1134   
16                       6715 6TH ST  95673    CA     2      1     844   
17           6236 LONGFORD DR Unit 1  95621    CA     2      1     795   
18                   250 PERALTA AVE  95833    CA     2      1     588   
19                   113 LEEWILL AVE  95673    CA     3      2    1356   
20                6118 STONEHAND AVE  95621    CA     3      2    1118   
21                 4882 BANDALIN WAY  95823    CA     4      2    1329   
22                   7511 OAKVALE CT  95660    CA     4      2    1240   
23                      9 PASTURE CT  95834    CA     3      2    1601   
24                3729 BAINBRIDGE DR  95660    CA     3      2     901   
25                3828 BLACKFOOT WAY  95843    CA     3      2    1088   
26                   4108 NORTON WAY  95820    CA     3      1     963   
27                  1469 JANRICK AVE  95832    CA     3      2    1119   
28                     9861 CULP WAY  95827    CA     4      2    1380   
29             7825 CREEK VALLEY CIR  95828    CA     3      2    1248   
..                               ...    ...   ...   ...    ...     ...   
955                  2100 BEATTY WAY  95747    CA     3      2    1371   
956              6920 GILLINGHAM WAY  95660    CA     3      1    1310   
957                 82 WILDFLOWER DR  95632    CA     3      2    1262   
958                  8652 BANTON CIR  95624    CA     4      2    1740   
959              8428 MISTY PASS WAY  95843    CA     3      2    1517   
960                7958 ROSEVIEW WAY  95828    CA     3      2    1450   
961                    9020 LUKEN CT  95624    CA     3      2    1416   
962              7809 VALLECITOS WAY  95828    CA     3      1     888   
963               8445 OLD AUBURN RD  95610    CA     3      2    1882   
964                  10085 ATKINS DR  95757    CA     3      2    1302   
965              9185 CERROLINDA CIR  95758    CA     3      2    1418   
966                 9197 CORTINA CIR  95678    CA     3      2       0   
967                  5429 HESPER WAY  95608    CA     4      2    1319   
968                 1178 WARMWOOD CT  95632    CA     4      2    1770   
969                    4900 ELUDE CT  95842    CA     4      2    1627   
970                    3557 SODA WAY  95834    CA     0      0       0   
971             3528 SAINT GEORGE DR  95821    CA     3      1    1040   
972                7381 WASHBURN WAY  95660    CA     3      1     960   
973             2181 WINTERHAVEN CIR  95682    CA     3      2       0   
974                 7540 HICKORY AVE  95662    CA     3      1    1456   
975              5024 CHAMBERLIN CIR  95757    CA     3      2    1450   
976                2400 INVERNESS DR  95648    CA     3      2    1358   
977                  5 BISHOPGATE 

In [99]:
real_state.drop([1,2,3],axis=0)

street             city    zip state  beds  \
0                       3526 HIGH ST       SACRAMENTO  95838    CA     2   
4                    6001 MCMAHON DR       SACRAMENTO  95824    CA     2   
5                 5828 PEPPERMILL CT       SACRAMENTO  95841    CA     3   
6                6048 OGDEN NASH WAY       SACRAMENTO  95842    CA     3   
7                      2561 19TH AVE       SACRAMENTO  95820    CA     3   
8    11150 TRINITY RIVER DR Unit 114   RANCHO CORDOVA  95670    CA     2   
9                       7325 10TH ST        RIO LINDA  95673    CA     3   
10                  645 MORRISON AVE       SACRAMENTO  95838    CA     3   
11                     4085 FAWN CIR       SACRAMENTO  95823    CA     3   
12                   2930 LA ROSA RD       SACRAMENTO  95815    CA     1   
13                     2113 KIRK WAY       SACRAMENTO  95822    CA     3   
14               4533 LOCH HAVEN WAY       SACRAMENTO  95842    CA     2   
15                    7340 HAMDEN PL       SACRAMENTO  95842    CA     2   
16                       6715 6TH ST        RIO LINDA  95673    CA     2   
17           6236 LONGFORD DR Unit 1   CITRUS HEIGHTS  95621    CA     2   
18                   250 PERALTA AVE       SACRAMENTO  95833    CA     2   
19                   113 LEEWILL AVE        RIO LINDA  95673    CA     3   
20                6118 STONEHAND AVE   CITRUS HEIGHTS  95621    CA     3   
21                 4882 BANDALIN WAY       SACRAMENTO  95823    CA     4   
22                   7511 OAKVALE CT  NORTH HIGHLANDS  95660    CA     4   
23                      9 PASTURE CT       SACRAMENTO  95834    CA     3   
24                3729 BAINBRIDGE DR  NORTH HIGHLANDS  95660    CA     3   
25                3828 BLACKFOOT WAY         ANTELOPE  95843    CA     3   
26                   4108 NORTON WAY       SACRAMENTO  95820    CA     3   
27                  1469 JANRICK AVE       SACRAMENTO  95832    CA     3   
28                     9861 CULP WAY       SACRAMENTO  95827    CA     4   
29             7825 CREEK VALLEY CIR       SACRAMENTO  95828    CA     3   
30      5201 LAGUNA OAKS DR Unit 140        ELK GROVE  95758    CA     2   
31                    6768 MEDORA DR  NORTH HIGHLANDS  95660    CA     3   
32                  3100 EXPLORER DR       SACRAMENTO  95827    CA     3   
..                               ...              ...    ...   ...   ...   
955                  2100 BEATTY WAY        ROSEVILLE  95747    CA     3   
956              6920 GILLINGHAM WAY  NORTH HIGHLANDS  95660    CA     3   
957                 82 WILDFLOWER DR             GALT  95632    CA     3   
958                  8652 BANTON CIR        ELK GROVE  95624    CA     4   
959              8428 MISTY PASS WAY         ANTELOPE  95843    CA     3   
960                7958 ROSEVIEW WAY       SACRAMENTO  95828    CA     3   
961                    9020 LUKEN CT        ELK GROVE  95624    CA     3   
962              7809 VALLECITOS WAY       SACRAMENTO  95828    CA     3   
963               8445 OLD AUBURN RD   CITRUS HEIGHTS  95610    CA     3   
964                  10085 ATKINS DR        ELK GROVE  95757    CA     3   
965              9185 CERROLINDA CIR        ELK GROVE  95758    CA     3   
966                 9197 CORTINA CIR        ROSEVILLE  95678    CA     3   
967                  5429 HESPER WAY       CARMICHAEL  95608    CA     4   
968                 1178 WARMWOOD CT             GALT  95632    CA     4   
969                    4900 ELUDE CT       SACRAMENTO  95842    CA     4   
970                    3557 SODA WAY       SACRAMENTO  95834    CA     0   
971             3528 SAINT GEORGE DR       SACRAMENTO  95821    CA     3   
972                7381 WASHBURN WAY  NORTH HIGHLANDS  95660    CA     3   
973             2181 WINTERHAVEN CIR     CAMERON PARK  95682    CA     3   
974                 7540 HICKORY AVE       ORANGEVALE  95662    CA     3   
975              5024 CHAMBERLIN CIR        ELK GROVE  95757    CA     3   
97

In [ ]:
# panda functions

In [94]:
real_state.mean()

zip           95750.697462
beds              2.911675
baths             1.776650
sq__ft         1314.916751
price        234144.263959
latitude         38.607732
longitude      -121.355982
dtype: float64

In [95]:
real_state.median()

zip           95762.000000
beds              3.000000
baths             2.000000
sq__ft         1304.000000
price        213750.000000
latitude         38.626582
longitude      -121.376220
dtype: float64

In [97]:
real_state.min()

street                   1 KENNELFORD CIR
city                             ANTELOPE
zip                                 95603
state                                  CA
beds                                    0
baths                                   0
sq__ft                                  0
type                                Condo
sale_date    Fri May 16 00:00:00 EDT 2008
price                                1551
latitude                          38.2415
longitude                        -121.552
dtype: object

In [98]:
real_state.max()

street             9970 STATE HIGHWAY 193
city                               WILTON
zip                                 95864
state                                  CA
beds                                    8
baths                                   5
sq__ft                               5822
type                               Unkown
sale_date    Wed May 21 00:00:00 EDT 2008
price                              884790
latitude                          39.0208
longitude                        -120.598
dtype: object

In [102]:
def half(s):
    return 0.5*s

In [103]:
real_state[["price"]].apply(half)

price
0     29611.0
1     34106.0
2     34440.0
3     34653.5
4     40950.0
5     44960.5
6     45447.5
7     45501.0
8     47452.5
9     49468.5
10    50154.5
11    53125.0
12    53426.0
13    53751.0
14    54375.0
15    55350.0
16    56631.5
17    58125.0
18    60000.0
19    60815.0
20    61000.0
21    61341.0
22    61500.0
23    62050.0
24    62500.0
25    63320.0
26    63640.5
27    64500.0
28    65600.0
29    66000.0
..        ...
955  104125.0
956  104159.0
957  104673.5
958  105750.0
959  106000.0
960  106500.0
961  108000.0
962  108010.5
963  109500.0
964  109897.0
965  110000.0
966  110000.0
967  110000.0
968  110000.0
969  111500.0
970  112000.0
971  112000.0
972  112126.0
973  112250.0
974  112500.0
975  114000.0
976  114513.5
977  114750.0
978  115000.0
979  115000.0
980  116212.5
981  117000.0
982  117500.0
983  117650.5
984  117869.0

[985 rows x 1 columns]

In [104]:
real_state['city'].value_counts()

SACRAMENTO         439
ELK GROVE          114
LINCOLN             72
ROSEVILLE           48
CITRUS HEIGHTS      35
ANTELOPE            33
RANCHO CORDOVA      28
EL DORADO HILLS     23
GALT                21
NORTH HIGHLANDS     21
CARMICHAEL          20
ROCKLIN             17
FOLSOM              17
RIO LINDA           13
ORANGEVALE          11
PLACERVILLE         10
FAIR OAKS            9
CAMERON PARK         9
AUBURN               5
WILTON               5
GOLD RIVER           4
ELVERTA              4
GRANITE BAY          3
RANCHO MURIETA       3
WEST SACRAMENTO      3
POLLOCK PINES        3
EL DORADO            2
LOOMIS               2
FORESTHILL           1
MATHER               1
PENRYN               1
MEADOW VISTA         1
DIAMOND SPRINGS      1
SLOUGHHOUSE          1
GREENWOOD            1
SHINGLE SPRINGS      1
COOL                 1
GARDEN VALLEY        1
WALNUT GROVE         1
Name: city, dtype: int64

In [105]:
real_state['state'].value_counts()

CA    985
Name: state, dtype: int64

In [106]:
real_state.sort_values(by='price')

street             city    zip state  beds  baths  \
865     3720 VISTA DE MADERA          LINCOLN  95648    CA     3      3   
866           14151 INDIO DR      SLOUGHHOUSE  95683    CA     3      4   
580                  59 E ST          LINCOLN  95648    CA     3      2   
584               386 1ST ST          LINCOLN  95648    CA     0      0   
585               374 1ST ST          LINCOLN  95648    CA     0      0   
586      116 CRYSTALWOOD WAY          LINCOLN  95648    CA     0      0   
587      108 CRYSTALWOOD WAY          LINCOLN  95648    CA     0      0   
588      100 CRYSTALWOOD WAY          LINCOLN  95648    CA     0      0   
589       55 CRYSTALWOOD CIR          LINCOLN  95648    CA     0      0   
590       51 CRYSTALWOOD CIR          LINCOLN  95648    CA     0      0   
591       47 CRYSTALWOOD CIR          LINCOLN  95648    CA     0      0   
592       43 CRYSTALWOOD CIR          LINCOLN  95648    CA     0      0   
593       39 CRYSTALWOOD CIR          LINCOLN  95648    CA     0      0   
594       35 CRYSTALWOOD CIR          LINCOLN  95648    CA     0      0   
595       31 CRYSTALWOOD CIR          LINCOLN  95648    CA     0      0   
596       27 CRYSTALWOOD CIR          LINCOLN  95648    CA     0      0   
597       23 CRYSTALWOOD CIR          LINCOLN  95648    CA     0      0   
598       19 CRYSTALWOOD CIR          LINCOLN  95648    CA     0      0   
599       15 CRYSTALWOOD CIR          LINCOLN  95648    CA     0      0   
600        7 CRYSTALWOOD CIR          LINCOLN  95648    CA     0      0   
601        7 CRYSTALWOOD CIR          LINCOLN  95648    CA     0      0   
602        3 CRYSTALWOOD CIR          LINCOLN  95648    CA     0      0   
579                  51 E ST          LINCOLN  95648    CA     4      2   
582       63 CRYSTALWOOD CIR          LINCOLN  95648    CA     0      0   
581                  75 E ST          LINCOLN  95648    CA     3      2   
583               398 1ST ST          LINCOLN  95648    CA     0      0   
555       24 CRYSTALWOOD CIR          LINCOLN  95648    CA     0      0   
578                  43 E ST          LINCOLN  95648    CA     0      0   
577                  35 E ST          LINCOLN  95648    CA     0      0   
576                  27 E ST          LINCOLN  95648    CA     0      0   
..                       ...              ...    ...   ...   ...    ...   
854     203 CASCADE FALLS DR           FOLSOM  95630    CA     4      3   
853             1165 37TH ST       SACRAMENTO  95816    CA     2      1   
547            9360 MAGOS RD           WILTON  95693    CA     5      2   
329       5709 RIVER OAK WAY       CARMICHAEL  95608    CA     4      2   
153       868 HILDEBRAND CIR           FOLSOM  95630    CA     0      0   
855           9880 IZILDA CT       SACRAMENTO  95829    CA     5      4   
858           620 KESWICK CT      GRANITE BAY  95746    CA     4      3   
857         4620 BROMWICH CT          ROCKLIN  95677    CA     4      3   
859        4478 GREENBRAE RD          ROCKLIN  95677    CA     0      0   
856         1800 AVONDALE DR        ROSEVILLE  95747    CA     5      3   
154         6030 PALERMO WAY  EL DORADO HILLS  95762    CA     4      3   
155          4070 REDONDO DR  EL DORADO HILLS  95762    CA     4      3   
860           8432 BRIGGS DR        ROSEVILLE  95747    CA     5      3   
330          2981 WRINGER DR        ROSEVILLE  95661    CA     4      3   
331        8616 ROCKPORTE CT        ROSEVILLE  95747    CA     4      2   
861   200 CRADLE MOUNTAIN CT  EL DORADO HILLS  95762    CA     0      0   
548            104 CATLIN CT           FOLSOM  95630    CA     4      3   
156          4004 CRESTA WAY       SACRAMENTO  95864    CA     3      3   
549          4734 GIBBONS DR       CARMICHAEL  95608    CA     4      3   
550       4629 DORCHESTER LN      GRANITE BAY  95746    CA     5      3   
551      2400 COUNTRYSIDE DR      PLACERVILLE  95667    CA     3      2   
862   2065 IMPRESSIONIST WAY  EL DORADO HILLS  

In [107]:
real_state.sort_values(by='zip')

street            city    zip state  beds  baths  sq__ft  \
468   2231 COUNTRY VILLA CT          AUBURN  95603    CA     2      2    1255   
484      220 OLD AIRPORT RD          AUBURN  95603    CA     2      2     960   
325            1740 HIGH ST          AUBURN  95603    CA     3      3       0   
852             820 DANA CT          AUBURN  95603    CA     4      3       0   
833      1484 RADCLIFFE WAY          AUBURN  95603    CA     4      3    2278   
485          4622 MEYER WAY      CARMICHAEL  95608    CA     4      2    1559   
822          3621 WINTUN DR      CARMICHAEL  95608    CA     3      2    1655   
414  7110 STELLA LN Unit 15      CARMICHAEL  95608    CA     2      2    1000   
832          4748 SALEM WAY      CARMICHAEL  95608    CA     3      2    2334   
952       3230 SMATHERS WAY      CARMICHAEL  95608    CA     3      2    1296   
715           5532 ENGLE RD      CARMICHAEL  95608    CA     2      2    1637   
329      5709 RIVER OAK WAY      CARMICHAEL  95608    CA     4      2    2222   
738        5118 ROBANDER ST      CARMICHAEL  95608    CA     3      2    1676   
94             4010 ALEX LN      CARMICHAEL  95608    CA     2      2    1326   
694       5733 ANGELINA AVE      CARMICHAEL  95608    CA     3      1     972   
967         5429 HESPER WAY      CARMICHAEL  95608    CA     4      2    1319   
383     7032 FAIR OAKS BLVD      CARMICHAEL  95608    CA     3      2    1245   
784         2949 PANAMA AVE      CARMICHAEL  95608    CA     3      2    1502   
549         4734 GIBBONS DR      CARMICHAEL  95608    CA     4      3    3357   
219      5925 MALEVILLE AVE      CARMICHAEL  95608    CA     4      2    1120   
58        5332 SANDSTONE ST      CARMICHAEL  95608    CA     3      1    1152   
763         6326 APPIAN WAY      CARMICHAEL  95608    CA     3      2    1443   
474       5847 DEL CAMPO LN      CARMICHAEL  95608    CA     3      1    1713   
72        5907 ELLERSLEE DR      CARMICHAEL  95608    CA     3      1     936   
321          2109 HAMLET PL      CARMICHAEL  95608    CA     2      2    1598   
649     6824 OLIVE TREE WAY  CITRUS HEIGHTS  95610    CA     3      2    1410   
688       6019 CHESHIRE WAY  CITRUS HEIGHTS  95610    CA     4      3    1736   
258         6344 BONHAM CIR  CITRUS HEIGHTS  95610    CA     5      4    2085   
963      8445 OLD AUBURN RD  CITRUS HEIGHTS  95610    CA     3      2    1882   
233     7944 SYLVAN OAK WAY  CITRUS HEIGHTS  95610    CA     3      2    1317   
..                      ...             ...    ...   ...   ...    ...     ...   
60       4844 CLYDEBANK WAY        ANTELOPE  95843    CA     3      2    1215   
902         3604 KODIAK WAY        ANTELOPE  95843    CA     3      2    1206   
792      7921 DOE TRAIL WAY        ANTELOPE  95843    CA     5      3    3134   
499     4712 PISMO BEACH DR        ANTELOPE  95843    CA     5      3    2346   
500    4741 PACIFIC PARK DR        ANTELOPE  95843    CA     5      3    2347   
444       4508 OLD DAIRY DR        ANTELOPE  95843    CA     4      3    2026   
43       5708 RIDGEPOINT DR        ANTELOPE  95843    CA     2      2    1043   
208          3228 BAGGAN CT        ANTELOPE  95843    CA     3      2    1392   
658    4008 GREY LIVERY WAY        ANTELOPE  95843    CA     3      2    1669   
696       8716 LONGSPUR WAY        ANTELOPE  95843    CA     3      2    1479   
700  7901 GAZELLE TRAIL WAY        ANTELOPE  95843    CA     4      2    1953   
264       8108 FILIFERA WAY        ANTELOPE  95843    CA     4      3    1768   
261        5712 MELBURY CIR        ANTELOPE  95843    CA     3      2    1567   
257        5312 MARBURY WAY        ANTELOPE  95843    CA     3      2    1574   
729         4085 COUNTRY DR        ANTELOPE  95843    CA     4      3    1915   
735         8316 NORTHAM DR        ANTELOPE  95843    CA     3      2    1235   
959     8428 MISTY PASS WAY        ANTELOPE  95843    CA     3      2    1517   
736           4240 WINJE DR        ANTELOPE  95843  

In [108]:
# matplotlib

In [1]:
import numpy as np

In [3]:
from matplotlib import pyplot as plt

ImportError: cannot import name 'ft2font' from 'matplotlib' (C:\Users\Jewel81\AppData\Roaming\Python\Python37\site-packages\matplotlib\__init__.py)